### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by sbarisic** [sbarisic/UnityGame#2]
- [ ] Developer console
Quake style? (Optional)

- [ ] Features
    - [x] Save/load config from hard drive
        - [ ] Textual format like JSON or XML (Optional)
    - [ ] In-game HUD
    - [ ] Everything is animated
        - [ ] Bone animations? (Optional)
    - [x] Player character (Pawn)
    - [x] Non player characters (Pawn)
        - [ ] Friendly, non-friendly (Optional?)
    - [x] Movement physics for pawns
        Do not use physics engine for this (forces, acceleration...), it does not work well
        Collision detection can be used
    - [ ] Level can be modified at runtime (Optional)

- [x] Main menu
    - [x] Start game
    - [ ] Load game
    - [x] Settings/options
    - [x] Exit

- [x] In-game pause menu
    - [x] Resume game
    - [ ] Save game (Optional) (Checkpoint system?)
    - [ ] Load game
    - [x] Settings/options
    - [x] Exit

- [x] Settings menu
    - [ ] Graphics settings
        - [ ] Video resolution
        - [ ] Fullscreen/windowed
        - [ ] Shader config (Fancy) (Optional)
    - [x] Sound settings
        - [x] Music volume
        - [x] Sound effects volume
    - [ ] Gameplay settings
        - [ ] Global time scale (Optional)
        - [ ] Enable cheats (Optional) (Dev console?)
        - [ ] Different HUD/GUI styles (Optional)

- [ ] Levels
    - [ ] At least 3 levels with win/lose conditions
    - [ ] Save/load levels from hard drive (Optional)
        Correct serialization and deserialization of level data
        TODO: Research game state saving for Unity

    - [ ] Enable external level editing tools like Tiled https://www.mapeditor.org/ (Optional)

**Comment by sbarisic** [comment]
- [x] Art style for GUI elements
- [x] Art style for HUD elements
- [x] Generic game style, textures, art...

Side notes, do not mix different pixel art pixel sizes (i.e. 16x16 and 32x32 tilesets)
Alternatively, this may be fixed with a post processing shader to blend inconsistencies

https://itch.io/game-assets/free/tag-2d
http://www.famfamfam.com/
https://www.plot-generator.org.uk/story/
